name: Run MSI Smoke Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Print Chrome version
      run: chrome --version

    - name: Run Smoke Tests with TestNG
      run: mvn clean test -Dsurefire.suiteXmlFiles=testng-smoke.xml || true

    - name: Upload Surefire Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Surefire Reports
        path: target/surefire-reports/

    - name: Upload Extent Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Extent Report
        path: test-output/
